name : Scheduled Workflow

on:
workflow_dispatch:
schedule:
- cron: "30 9 * * 1-5"

jobs:
  demo:
    runs-on : ubuntu-latest

    steps:
      - name : Log time
      run : |
      current_date_time=$(date)
      echo "Current date and time: $current_date_time"
